<a href="https://colab.research.google.com/github/nixonguevara4-afk/programacion/blob/main/Copy_of_Untitled18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nixon Rojas-2231944
# -Bono 1

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([2, 4, 6]) #Vector columna
s

0    2
1    4
2    6
dtype: int64

In [ ]:
df = pd.DataFrame({"Pais": ["Alemania", "Colombia", "Japón"],
                   "Nombre": ["Nixon", "Laura", "Oliver"],
                   "Edad": [20, 27, 23]})
df

       Pais  Nombre  Edad
0  Alemania   Nixon    20
1  Colombia   Laura    27
2     Japón  Oliver    23

In [ ]:
df.head(1)  #primeras filas

       Pais Nombre  Edad
0  Alemania  Nixon    20

In [ ]:
df.tail(1)  #últimas filas

    Pais  Nombre  Edad
2  Japón  Oliver    23

In [ ]:
df.info()   #tipo de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Pais    3 non-null      object
 1   Nombre  3 non-null      object
 2   Edad    3 non-null      int64
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df.describe() #estadisticas para los que son variables cuantitativas

            Edad
count   3.000000
mean   23.333333
std     3.511885
min    20.000000
25%    21.500000
50%    23.000000
75%    25.000000
max    27.000000

In [ ]:
df.shape  #filas y columnas

(3, 3)

In [ ]:
df["Nombre"] #para imprimir la columna deseada en este caso nombre

0     Nixon
1     Laura
2    Oliver
Name: Nombre, dtype: object

In [ ]:
df[["Pais", "Nombre"]]  #seleccionar columnas

       Pais  Nombre
0  Alemania   Nixon
1  Colombia   Laura
2     Japón  Oliver

In [ ]:
df[df["Edad"] >= 23]  #seleccionar filas

       Pais  Nombre  Edad
1  Colombia   Laura    27
2     Japón  Oliver    23

In [ ]:
df[(df["Edad"] >= 20) & (df["Edad"] <= 23)]

       Pais  Nombre  Edad
0  Alemania   Nixon    20
2     Japón  Oliver    23

In [ ]:
import numpy as np

In [ ]:
data = {"nombre": ["Nixon", "Mariana", "Karen", None],
        "edad": [20, np.nan, 23, 30],
        "fruta": ["Guanabana", "Pera", None, "Banana"],
        "pais": [None, "Colombia", "Japón", "España"]}
data

{'nombre': ['Nixon', 'Mariana', 'Karen', None],
 'edad': [20, nan, 23, 30],
 'fruta': ['Guanabana', 'Pera', None, 'Banana'],
 'pais': [None, 'Colombia', 'Japón', 'España']}

In [ ]:
data1 = pd.DataFrame(data)
data1

    nombre  edad      fruta      pais
0    Nixon  20.0  Guanabana      None
1  Mariana   NaN       Pera  Colombia
2    Karen  23.0       None     Japón
3     None  30.0     Banana    España

In [ ]:
data1.isnull() #muestra los valores faltantes

   nombre   edad  fruta   pais
0   False  False  False   True
1   False   True  False  False
2   False  False   True  False
3    True  False  False  False

In [ ]:
data1.isnull().sum() #muestra cuantos valores faltan en cada columna

nombre    1
edad      1
fruta     1
pais      1
dtype: int64

In [ ]:
data2 = data1.dropna() #elimina las filas con valores faltantes, en este caso todos
data2

Empty DataFrame
Columns: [nombre, edad, fruta, pais]
Index: []

In [ ]:
data1.dropna(subset=["fruta"]) #elimina las filas con valores faltantes en la columna fruta

    nombre  edad      fruta      pais
0    Nixon  20.0  Guanabana      None
1  Mariana   NaN       Pera  Colombia
3     None  30.0     Banana    España

In [ ]:
data1["edad"] = data1["edad"].fillna(data1["edad"].mean()) #rellena los valores faltantes con la media de la columna
data1["nombre"] = data1["nombre"].fillna("Sin nombre")
data1

       nombre       edad      fruta      pais
0       Nixon  20.000000  Guanabana      None
1     Mariana  24.333333       Pera  Colombia
2       Karen  23.000000       None     Japón
3  Sin nombre  30.000000     Banana    España

In [ ]:
data1["pais"] = data1["pais"].replace("Japón", "JAPON") #remplaza los elementos
data1

       nombre       edad      fruta      pais
0       Nixon  20.000000  Guanabana      None
1     Mariana  24.333333       Pera  Colombia
2       Karen  23.000000       None     JAPON
3  Sin nombre  30.000000     Banana    España

In [ ]:
data3 = data1["pais"].drop_duplicates() #borra los duplicados en este caso no hay duplicados
data3

0        None
1    Colombia
2       JAPON
3      España
Name: pais, dtype: object

In [ ]:
data4 = {"nombre": ["Nixon", "Maria", "Angie"],
         "edad": [20, 21, 20],
         "ciudad":["Guapotá", "Girón", "La esperanza"]}
data4 = pd.DataFrame(data4)
data4

  nombre  edad        ciudad
0  Nixon    20       Guapotá
1  Maria    21         Girón
2  Angie    20  La esperanza

In [ ]:
data5 = data4.drop_duplicates() #tambien se puede borrar directamente
data5

  nombre  edad        ciudad
0  Nixon    20       Guapotá
1  Maria    21         Girón
2  Angie    20  La esperanza

In [ ]:
dfn = pd.DataFrame({"ID": [1, 2, 3, 4],
                    "nombre": ["Nixon", "LAURA", "Maria", "Karen"],
                    "edad": [20, 25, 23, 24],
                    "salario": [1000, 2000, 3000, 4000,],
                    "ciudad": ["Bucaramanga", " Medellin", "Bogota", "Cali"]})
dfn

   ID nombre  edad  salario       ciudad
0   1  Nixon    20     1000  Bucaramanga
1   2  LAURA    25     2000     Medellin
2   3  Maria    23     3000       Bogota
3   4  Karen    24     4000         Cali

In [ ]:
dfn["salario_anual"] = dfn["salario"] * 12
dfn["edad_doble"] = dfn["edad"].apply(lambda x: x*2)
dfn

   ID nombre  edad  salario       ciudad  salario_anual  edad_doble
0   1  Nixon    20     1000  Bucaramanga          12000          40
1   2  LAURA    25     2000     Medellin          24000          50
2   3  Maria    23     3000       Bogota          36000          46
3   4  Karen    24     4000         Cali          48000          48

In [ ]:
dfn = dfn.rename(columns = {"edad": "age"})
dfn

   ID nombre  age  salario       ciudad  salario_anual  edad_doble
0   1  Nixon   20     1000  Bucaramanga          12000          40
1   2  LAURA   25     2000     Medellin          24000          50
2   3  Maria   23     3000       Bogota          36000          46
3   4  Karen   24     4000         Cali          48000          48

In [ ]:
dfn["nombre"] = dfn["nombre"].str.lower()
dfn["nombre"] = dfn["nombre"].str.strip()
dfn["nombre"] = dfn["nombre"].str.replace("Nixon", "nixon")

In [ ]:
  dfn

   ID nombre  age  salario       ciudad  salario_anual  edad_doble
0   1  nixon   20     1000  Bucaramanga          12000          40
1   2  laura   25     2000     Medellin          24000          50
2   3  maria   23     3000       Bogota          36000          46
3   4  karen   24     4000         Cali          48000          48

In [ ]:
grupo = dfn.groupby("ciudad")["salario"].mean()
grupo

ciudad
 Medellin      2000.0
Bogota         3000.0
Bucaramanga    1000.0
Cali           4000.0
Name: salario, dtype: float64

# ventajas y desventajas para la implementación de algoritmos

Pandas es una biblioteca enfocada en la manipulación y análisis de datos estructurados mediante tablas llamadas DataFrames y Pandas es una biblioteca enfocada en la manipulación y análisis de datos estructurados mediante tablas llamadas DataFrames

# **ventajas de los algotimos**



*  Permiten realizar operaciones matemáticas de manera rápida y facilita la organización y transformación de datos.
*   Numpy es la base de muchas bibliotecas de análisis de datos.



*   Ofrecen funciones optimizadas que mejoran el rendimiento computacional.
*   Permiten trabajar con grandes cantidades de información.

# **Desventajas de los algoritmos**



*   Puede consumir mucha memoria con grandes volúmenes de datos.
*   El manejo de bloques de codigos avanzadas puede volverse complejo en proyectos grandes.


*   Un uso inadecuado puede generar algoritmos poco eficientes.